# Data from City of Raleigh Public Works department GIS.  These coordinates were emailed from them and are not 100% accurate, some duplicates etc...

Thing.create(city_id:     1, lng: -78.5651, lat: 35.7682)
